### ISSUE TITLE
Connection pooling leads to confused transaction isolation levels

### ISSUE THREAD

**Issue by jan-jockusch** [psycopg/ZPsycopgDA#4] opened 2016-05-06 06:53 UTC
There is an issue with this DA which leads to several Zope Connection objects to share pooled connections, even when they have different transaction isolation levels.

This leads to unexpected behaviour, because transaction isolation levels change seemingly at random.

A test sequence which performs "select setting from pg_settings where name = 'transaction_isolation'" on different connectors exposes the problem.

I have written a patch which fixes this, and I would be glad to contribute, but this editor does not allow me to attach a patch file...

How can I pass the patch to you?

**Comment by fogzot** [comment] 2016-05-06 07:58
Just clone our repo and send a pull request here on GitHub. If you don't want to do that just format a patch using git and attach it here.

**Comment by jan-jockusch** [comment] 2016-05-10 05:43
Hello Federico,

thank you for the quick reply. I have cloned the git repository and used
git to diff my changes. I tried to comment everything I did, and it's
not all elegant...

The patch is working already in one production environment.

A test inside Zope confirms it is working as intended. To replicate, add
two connectors using the same DSN but different transaction isolation
levels. Then periodically test the current setting of each connector
with "select setting from pg_settings where
name='transaction_isolation'". In the old version, the result is not
reliable, with the patch, it is.

Thank you for considering the patch. I realize that pool.py becomes a
lot less elegant with the changes, but the parameter passing is
necessary, because each pool has more variables than just the DSN.

Any feedback you have on the patch I'd be very glad to hear, if you need
more info from me, just ask.

Cheers,

Ján
[ZPsycopgDA.patch.zip](https://github.com/psycopg/ZPsycopgDA/files/256431/ZPsycopgDA.patch.zip)

**Comment by viktordick** [comment] 2020-06-13 18:09
Is this package still maintained? The last commits were in 2015.

The changes mentioned in this issue have by now seen quite some development, see [https://github.com/perfact/ZPsycopgDA](url). Is there a chance to someday submit them as pull request? I would try to prepare the PR if there is still some interest in it.

The changes include
- Using a `ThreadedConnectionPool` so connectors between different threads on the same worker are not confused. Also uses the physical path of the `Database Connection` object so different connection objects actually create separate connections and are not confused.
- Better handling of OperationalErrors. In the current implementation, these simply close the connection without aborting the request. This can have the effect of simply starting a new transaction on the relational database while the transaction in Zope is in the middle of execution.
- Support for autocommit connectors, read-only connectors and two-phase-commit
- Throwing an error if results were cut off by `max_rows` since it is better than simply obtaining incomplete results and producing inconsistencies

I probably forgot some changes, but before really working towards making our fork mergeable (maybe in several smaller steps) I wanted to ask if this project is still alive and the maintainers are interested.

**Comment by dvarrazzo** [comment] 2020-06-14 04:01
I am the person who is more actively involved in maintaining psycopg2 and I don't have knowledge or resources to maintain the Zope adapter. I have never used Zope professionally, I have no idea of the life cycle of a database connection within the Zope framework, I cannot be the judge of whether a change would be good or bad, whether it would be welcome or not bu the users, what would be its side effects.

Several years ago I tried gauging the interest in maintaining the package by asking people from a professional Zope shop about their interest in having this package maintained and their answer was that there was little as - according to them - Zope people use the SQLAlchemy wrapper. I don't feel like being a champion in which I have no personal interest and the supposed users are not interest either. Would you be?

As far as I know every merge request we receive - a very rare occurrence - could break everything for everyone else: there is no way to verify the quality of the proposals received - which again are just one every few years. So as far as I can see, more than lack of interest in maintaining the package there is lack of people wanting the package.

If you would like to do something meaningful please create a test suite for the Zope adapter and propose a MR to have it running on Travis; create a few tests to verify the current behaviour, propose merge requests and tests verifying that the change proposed are improvements and don't cause regressions. I am not interested in putting my name on any work released with lower quality than this.

My involvement in maintaining the project can be with merging proposed MR and release packages when it's ready. If these MR don't exist, if QA doesn't exist, I can't put it there for the Zope people. I am available to do more only with financial support, not for free: my free time can only be used for project I have personal interest in.

**Comment by viktordick** [comment] 2024-04-01 09:35
After this long time, I was trying to see what adding QA here would entail. And failed due to the code not working with Python 3.
My guess is that whoever still uses this with Python 2 has the version pinned anyway and is providing at most life-sustaining measures to the systems using it (at least that is our use case).
In our fork (https://github.com/perfact/ZPsycopgDA), we have put some work into making this compatible with Python 3 and Zope 4, which is in productive use on several dozens of systems. Although I just noticed that we have not touched the `test` directory.

Maybe we should just talk about archiving this original repository in its current state and coordinating which of the several forks deserves to be the successor. On first glance, https://github.com/dataflake/Products.ZPsycopgDA seems to maybe be an even better maintained and up-to-date fork. I guess getting our required features merged there will be a less daunting task than getting them included here.

Archiving the repository will make sure no PRs meant for `Products.ZPsycopgDA` are accidentally created against this repo instead.

**Comment by dvarrazzo** [comment] 2024-04-01 21:54
@viktordick the dataflake fork seems more maintained indeed and has a PyPI release. I suggest you propose them a MR.

**Comment by jan-jockusch** [comment] 2024-04-10 07:28
Closing this issue. We'll attempt looking at dataflake's fork. Is this actually an archived repo?

**Closed as completed** 2024-04-10 07:28 UTC
